const rawRounds = [
  "            \n                \n                    \n                    Ballesteros enanos N2\n                    538\n                \n                \n                    La milicia de la ciudad elimina a 5 Ballesteros enanos N2 (-10 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n                    \n            \n                \n                Adri N3\n                \n            \n            \n                                        \n                                        El héroe Adri N3 elimina a 132 Goblins N1 (-132 niveles)\n            \n            \n                \n                Goblins N1\n                1300\n            \n        \n            \n        \n            \n            Enanos elite N4\n            29\n        \n        \n                                \n                                        \n                    \n            40 Orcos en jabalies N3  eliminan a 7 Enanos elite N4 (-28 niveles)\n        \n        \n            \n            Orcos en jabalies N3\n            40\n        \n    \n    \n        \n            \n            Enanos elite N4\n            22\n        \n        \n                                \n                    \n            22 Enanos elite N4  eliminan a 6 Orcos en jabalies N3 (-18 niveles)\n        \n        \n            \n            Orcos en jabalies N3\n            40\n        \n    \n",
  "            \n                \n                    \n                    Guerreros enanos N1\n                    113\n                \n                \n                    La milicia de la ciudad elimina a 10 Guerreros enanos N1 (-10 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n                    \n            \n                \n                Adri N3\n                \n            \n            \n                                        \n                                        El héroe Adri N3 elimina a 56 Orcos guerreros N2 (-112 niveles)\n            \n            \n                \n                Orcos guerreros N2\n                375\n            \n        \n            \n        \n            \n            Enanos fanaticos N3\n            313\n        \n        \n                                \n                    \n            319 Orcos guerreros N2  eliminan a 44 Enanos fanaticos N3 (-132 niveles)\n        \n        \n            \n            Orcos guerreros N2\n            319\n        \n    \n    \n        \n            \n            Enanos fanaticos N3\n            249\n        \n        \n                                \n                                        \n                    \n            249 Enanos fanaticos N3  eliminan a 92 Orcos guerreros N2 (-184 niveles)\n        \n        \n            \n            Orcos guerreros N2\n            319\n        \n    \n        \n        20 Enanos fanaticos han huido (-60 niveles)        \n            \n                \n                Enanos fanaticos N3\n                249\n            \n            \n                \n                Segundo ataque de Enanos fanaticos N3 provoca 17 bajas (-34 niveles)\n            \n            \n                \n                Orcos guerreros N2\n                227\n            \n        \n        ",
  "            \n                \n                    \n                    Ballesteros enanos N2\n                    533\n                \n                \n                    La milicia de la ciudad elimina a 5 Ballesteros enanos N2 (-10 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n                \n        \n            \n            Ballesteros enanos N2\n            528\n        \n        \n                                \n                    \n            528 Ballesteros enanos N2  disparan y eliminan a 275 Goblins N1 (-275 niveles)\n        \n        \n            \n            Goblins N1\n            1168\n        \n    \n",
  "            \n                \n                    \n                    Ballesteros enanos N2\n                    528\n                \n                \n                    La milicia de la ciudad elimina a 5 Ballesteros enanos N2 (-10 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n                \n        \n            \n            Enanos fanaticos N3\n            249\n        \n        \n                                \n                    \n            893 Goblins N1  eliminan a 61 Enanos fanaticos N3 (-183 niveles)\n        \n        \n            \n            Goblins N1\n            893\n        \n    \n",
  "            \n            Tras haber actuado todas las tropas posibles la milicia reduce la intensidad del ataque            \n                \n                    \n                    Enanos elite N4\n                    22\n                \n                \n                    La milicia de la ciudad elimina a 1 Enanos elite N4 (-4 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n                    \n            \n                \n                Adri N3\n                \n            \n            \n                                El héroe Adri N3 elimina a 132 Goblins N1 (-132 niveles)\n            \n            \n                \n                Goblins N1\n                893\n            \n        \n        ",
  "            \n                \n                    \n                    Enanos fanaticos N3\n                    188\n                \n                \n                    La milicia de la ciudad elimina a 2 Enanos fanaticos N3 (-6 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n                    \n        Chequeo de moral:  El héroe Adri N3 falla el chequeo y se retira del combate",
  "            \n                \n                    \n                    Enanos fanaticos N3\n                    186\n                \n                \n                    La milicia de la ciudad elimina a 2 Enanos fanaticos N3 (-6 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n            ",
  "            \n                \n                    \n                    Guerreros enanos N1\n                    103\n                \n                \n                    La milicia de la ciudad elimina a 7 Guerreros enanos N1 (-7 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n            ",
  "            \n                \n                    \n                    Enanos fanaticos N3\n                    184\n                \n                \n                    La milicia de la ciudad elimina a 2 Enanos fanaticos N3 (-6 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n            ",
  "            \n                \n                    \n                    Guerreros enanos N1\n                    96\n                \n                \n                    La milicia de la ciudad elimina a 7 Guerreros enanos N1 (-7 niveles)\n                \n                \n                    \n                    Milicia de Port mangudo\n                \n            \n            "
];

function cleanString(input) {
  return input.replace(/\s{2,}/g, ' ').trim();
}

function processRounds(rawRounds) {
  return rawRounds.map((round, index) => {
    const cleanedRound = cleanString(round);
    return `Round ${index + 1}: ${cleanedRound}`;
  });
}

const processedRounds = processRounds(rawRounds);
console.log(processedRounds.join("\n\n"));
